FROM node:22-alpine AS dev

WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
EXPOSE 3002
CMD ["npm", "run", "dev", "--", "--host"]

FROM node:22-alpine AS build
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
RUN npm run build

FROM scratch AS dist
COPY --from=build /app/dist /dist
