---
name: "Picnic Swipe"
version: "1.0.1"
slug: "picnic"
description: "Swipe Picnic products into your basket"
url: "https://github.com/stevendejongnl/madebysteven-ha-addons"
arch:
  - amd64
  - aarch64
ingress: true
ingress_port: 8000
map:
  - homeassistant_config:ro
